version: '3.8'

services:
  app:
    build: .
    ports:
      - "8088:8000"
    environment:
      - DATABASE_URL=postgresql://userapp:1234@db:5432/app_database
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: userapp
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: app_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: